incsrc "animationIds.asm"
incsrc "tileIds.asm"
incsrc "chars.asm"
incsrc "constants.asm"
incsrc "items.asm"
incsrc "funcs.asm"
incsrc "macros.asm"
incsrc "eventIds.asm"
incsrc "soundIds.asm"
incsrc "lairIds.asm"
incsrc "mapNumbers.asm"

incsrc "structs.asm"
incsrc "labels.asm"
