%define_enum(Items,
    Empty,
    LifeSword,PsychoSword,CriticalSword,LuckyBlade,ZantetsuSword,SpiritSword,RecoverySword,SoulBlade,
    IronArmor,IceArmor,BubbleArmor,MagicArmor,MysticArmor,LightArmor,ElementalArmor,SoulArmor,
    FlameBall,LightArrow,MagicFlare,Rotator,SparkBomb,FlamePillar,Tornado,Phoenix,
    GoatsFood,HarpString,APass,DreamRod,LeosBrush,TurbosLeaves,MolesRibbon,BigPearl,MermaidsTears,MushroomShoes,
    AirshipKey,ThunderRing,DeliciousSeeds,CatLeaves,DoorKey,PlatinumCard,VipCard,EmblemA,EmblemB,EmblemC,
    EmblemD,EmblemE,EmblemF,EmblemG,EmblemH,RedHotMirror,RedHotBall,RedHotStick,PowerBracelet,ShieldBracelet,
    SuperBracelet,MedicalHerb,StrangeBottle,BrownStone,GreenStone,BlueStone,SilverStone,PurpleStone,BlackStone,MagicBell)
